"use client";
import Header from "@/components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import AppContext from "@/utils/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fashion Store",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          <Header />
          {children}
          <Footer />
        </AppContext>
      </body>
    </html>
  );
}
